src/Entity/Blog.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity()]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Contenu = null;

    #[ORM\Column(length: 800)]
    private ?string $Image = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Wishlist.php
<?php

namespace App\Entity;

use App\Repository\WishlistRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WishlistRepository::class)]
class Wishlist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'wishlists')]
    private ?Produit $produits = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduits(): ?Produit
    {
        return $this->produits;
    }

    public function setProduits(?Produit $produits): self
    {
        $this->produits = $produits;

        return $this;
    }
}

src/Controller/WishlistController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Wishlist;
use App\Repository\ProduitRepository;
use App\Repository\WishlistRepository;
use Doctrine\ORM\EntityManagerInterface;

class WishlistController extends AbstractController
{
    #[Route('/wishlist', name: 'app_wishlist')]
    public function index(ProduitRepository $repo,WishListRepository $repoWishList): Response
    {
        $liste = [];

        foreach ($repoWishList as $item) {
          
                $liste[] = [
                    'produit' => $item->getProduits(),
                ];
        }
   
        return $this->render('wishlist/index.html.twig', [
            'liste'=>$repoWishList->findAll()
        ]);
    }

    #[Route('/addWishlist/{id}', name: 'app_addWishlist')]
    public function addWishlist($id,ProduitRepository $repo,WishListRepository $repoWishList,EntityManagerInterface $manager)
    {
        $produit = $repo->find($id);
       
        if($repoWishList->findByProduct($produit))
        {  
            $wishlist= $repoWishList->findByProduct($produit);
            $manager->remove($wishlist);
            $manager->flush();
        }
        else{
           
            $wishlist = new Wishlist();
            $wishlist->setProduits($repo->find($id));
            $manager->persist($wishlist);
            $manager->flush();
      
        }
        return $this->redirectToRoute('app_wishlist');
        
    }
}

templates/wishlist/index.html.twig
{% extends 'frontBase.html.twig' %}
{% block title %}Magasin{% endblock %}

{% block content %}
<!-- banner-section start -->
<section id="banner-section" class="inner-banner profile features shop">
    <div class="ani-img">
        <img class="img-1" src="{{asset('front/images/banner-circle-1.png')}}" alt="icon">
        <img class="img-2" src="{{asset('front/images/banner-circle-2.png')}}" alt="icon">
        <img class="img-3" src="{{asset('front/images/banner-circle-2.png')}}" alt="icon">
    </div>
    <div class="banner-content d-flex align-items-center">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="main-content">
                        <h1>Shop</h1>
                        <div class="breadcrumb-area">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb d-flex justify-content-center">
                                    <li class="breadcrumb-item"><a href="">Accueil</a></li>
                                    <li class="breadcrumb-item"><a href="{{ path('app_afficherCategorieFront') }}">Magasin</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Wishlist</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- banner-section end -->



 <!-- Featured Products Start -->
 <section id="featured-products" class="pt-120 pb-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 d-flex align-items-center">
                <div class="section-header text-center">
                    <h2 class="title">Vos produits préférés</h2>
                </div>
            </div>
        </div>
        <div class="row cus-m">
            {% for prod in liste %}
           
            <div class="col-lg-4 col-md-6">
                
                <div class="single-item" style="min-height: 450px;max-height: 450px"> 
                    <a href="{{path('app_detailProduitFront',{ id:prod.getProduits().getId() })}}">
                    <span class="new">Vous avez aimé ce produit</span>
                    <div class="img-area text-center" style="min-height: 250px;max-height:250px">
                        <img src="{{asset('eshop/produit/'~prod.getProduits().image)}}" alt="image" width="90%">
                    </div>
                    <div class="bottom-item text-center">
                        
                        <a href="{{path('app_detailProduitFront',{ id:prod.getProduits().getId() })}}" ><h6>{{ prod.getProduits().getNomProduit() }}</h6></a>
                        <p class="text-sm">{{ prod.getProduits().getCategorie().getNomCategorie()}}</p>
                          
                        <div class="bottom-area d-flex align-items-center justify-content-between">
                            <h5>{{ prod.getProduits().getPrix() }} DT</h5>
                        </div>
                    </div>
                </a>
                </div>
            </div>
        
            {% endfor %} 
           
        </div>
    </div>
</section>
<!-- Featured Products End -->
{% endblock %}